# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: krovs
description: > # this means to ignore newlines until "baseurl:"
  krovs' thingies
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://krovs.dev" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Collections
collections_dir: _collections

collections:
  dev:
    output: true
    permalink: /:collection/:name
  h1ctf:
    output: true
    permalink: /:collection/:name
  h1:
    output: true
    permalink: /:collection/:name
  htb:
    output: true
    permalink: /:collection/:name