# Site settings
title: Robert Krovs
email: krovs.dev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Robert Krovs' portfolio
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://krovs.com" # the base hostname & protocol for your site
timezone: Europe/Madrid
permalink: pretty
# Build settings
markdown: kramdown
encoding: utf-8
