# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Roberto Otero
email: krovs.dev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Roberto Otero's portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rotero.dev" # the base hostname & protocol for your site
twitter_username: rkrovs
github_username:  krovs

# Build settings
markdown: kramdown
